# Generated by Django 2.0.2 on 2018-02-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
