# Generated by Django 2.0.2 on 2018-02-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0002_auto_20180224_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='hangouts', to='hangout.Tag'),
        ),
    ]
