# Generated by Django 2.0.2 on 2018-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0003_auto_20180224_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='description',
            field=models.CharField(max_length=140),
        ),
    ]
