# Generated by Django 2.0.2 on 2018-02-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangout', '0004_auto_20180226_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
